#BLOCK 1: WORKFLOW METADATA
name: Deploy-blog
# BLOCK 2: TRIGGERS (When to Run)
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

#BLOCK 3: JOBS (What Work to Do)
jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
      #BLOCK 4: STEPS (Individual Actions)
      - name: Checkout code
        uses: actions/checkout@v3

      #BLOCK 5: SETUP NODE.JS
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: "18"
          cache: "npm" # don't re-download packages next time

      #BLOCK 6: INSTALL DEPENDENCIES
      - name: Install Dependencies
        run: npm ci
      
      #BLOCK 7: RUN LINTER
      - name: run Linter  #Linter is the code quality checker, syntax err, bugs etc.
        run: npm run lint || echo "No lint script found" # || is the login OR operator in bash. 

      #BLOCK 8: BUILD PROJECT
      - name: Build Project
        run: npm run build
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
      #BLOCK 9: BUILD IMAGE
      - name: Build Docker Images
        run: |
          docker build -t murtaza007/my-blog-frontend .
          docker build -t murtaza007/my-blog-backend ./server
      #BLOCK 10: LOGIN TO DOCKER HUB
      - name: Login to dockerhub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      #BLOCK 11: PUSHING IMAGE TO DOCKER HUB
      - name: Push Images
        run: |
          docker push murtaza007/my-blog-frontend
          docker push murtaza007/my-blog-backend
      #BLOCK 12: LOGIN TO EC2 INSTANCE
      - name: SSH to EC2 instance and deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # removing the current container 
            docker stop my-blog-backend || true
            docker rm my-blog-backend || true
            docker stop my-blog-frontend || true
            docker rm my-blog-frontend || true
            # removing the current images
            docker rmi murtaza007/my-blog-backend || true
            docker rmi murtaza007/my-blog-frontend || true
            # pulling the new images
            docker pull murtaza007/my-blog-frontend
            docker pull murtaza007/my-blog-backend
            # running new container
            docker run -d -p 80:80 --name my-blog-c-frontend murtaza007/my-blog-frontend
            docker run -d -p 3000:3000 --name my-blog-c-backend murtaza007/my-blog-backend

  
